### ISSUE TITLE
Downloaded NWM_channel_hydrofabric.tar.gz is v2.1 instead of v2.0 now.

### ISSUE THREAD

**Issue by cuill** [schism-dev/pyschism#25]
To use v2.0, the wget.download should be changed to:

wget.download(
                    'https://www.nohrsc.noaa.gov/pub/staff/keicher/NWM_live/'
                    'web/data_tools/NWM_v2.0_channel_hydrofabric.tar.gz',)

**Comment by jreniel** [comment]
Thanks. Just today I spent a good amount of time back developing pyschism. I had to take a break.

**Comment by jreniel** [comment]
On the current version, it's actually pulling a tarfile from https://www.nohrsc.noaa.gov/pub/staff/keicher/NWM_live/web/data_tools/NWM_channel_hydrofabric.tar.gz which is supposed always be the latest. Since this link cached, in order to updated, we might need to delete the tar file from cache. See: https://github.com/schism-dev/pyschism/blob/develop/pyschism/forcing/source_sink/nwm.py#L438-L441
