### ISSUE TITLE
Stations input file name issue

### ISSUE THREAD

**Issue by SorooshMani-NOAA** [schism-dev/pyschism#33]
I noticed that in PySCHISM the station input file for SCHISM is written as `stations.in` instead of `station.in` (note the extra "**s**").
https://github.com/schism-dev/pyschism/blob/ec00dffb251e49759a1162eff4e911c82a7d0cf2/pyschism/driver.py#L532

In older versions e.g. https://github.com/schism-dev/pyschism/commit/0f5bf18195872ec2737593d44834b3273f74a4b9, it used to write to `station.in`:
https://github.com/schism-dev/pyschism/blob/0f5bf18195872ec2737593d44834b3273f74a4b9/pyschism/driver.py#L464-L466

I didn't find any reference to `stations.in` in SCHISM code, so I'm assuming this is a bug. @josephzhang8, does SCHISM accept `stations.in` instead of `station.in` as station input file?

**Comment by josephzhang8** [comment]
You are right Soroosh; it should be station.in. Linlin/Jaime can fix it. Thx.


-Joseph

Joseph Zhang
Office: (804) 684 7466
Web: schism.wiki

From: Soroosh Mani ***@***.***
Sent: Thursday, December 23, 2021 11:05 AM
To: schism-dev/pyschism ***@***.***>
Cc: Y. Joseph Zhang ***@***.***>; Mention ***@***.***>
Subject: [schism-dev/pyschism] Stations input file name issue (Issue #33)


[EXTERNAL to VIMS received message]


I noticed that in PySCHISM the station input file for SCHISM is written as stations.in instead of station.in (note the extra "s").
https://github.com/schism-dev/pyschism/blob/ec00dffb251e49759a1162eff4e911c82a7d0cf2/pyschism/driver.py#L532<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fschism-dev%2Fpyschism%2Fblob%2Fec00dffb251e49759a1162eff4e911c82a7d0cf2%2Fpyschism%2Fdriver.py%23L532&data=04%7C01%7Cyjzhang%40vims.edu%7Ca0f86e11570441e61e0408d9c62dfa1b%7C8cbcddd9588d4e3b9c1e2367dbdf1740%7C0%7C0%7C637758723058571427%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=QH3J8T5UWt93HaMtHYaTjiTQXot89AUnMPw3M9Al%2B1E%3D&reserved=0>

In older versions e.g. 0f5bf18<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fschism-dev%2Fpyschism%2Fcommit%2F0f5bf18195872ec2737593d44834b3273f74a4b9&data=04%7C01%7Cyjzhang%40vims.edu%7Ca0f86e11570441e61e0408d9c62dfa1b%7C8cbcddd9588d4e3b9c1e2367dbdf1740%7C0%7C0%7C637758723058571427%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=bAt2z8X%2BCnFZS9ZdSYkfi1CDKjBEh%2B3hHDweGQdxDHs%3D&reserved=0>, it used to write to station.in:
https://github.com/schism-dev/pyschism/blob/0f5bf18195872ec2737593d44834b3273f74a4b9/pyschism/driver.py#L464-L466<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fschism-dev%2Fpyschism%2Fblob%2F0f5bf18195872ec2737593d44834b3273f74a4b9%2Fpyschism%2Fdriver.py%23L464-L466&data=04%7C01%7Cyjzhang%40vims.edu%7Ca0f86e11570441e61e0408d9c62dfa1b%7C8cbcddd9588d4e3b9c1e2367dbdf1740%7C0%7C0%7C637758723058571427%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=nZ9bDQ2mh2XOlCNk6FQDf7cmNBWWD0CYPA5PIutth0k%3D&reserved=0>

I didn't find any reference to stations.in in SCHISM code, so I'm assuming this is a bug. @josephzhang8<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjosephzhang8&data=04%7C01%7Cyjzhang%40vims.edu%7Ca0f86e11570441e61e0408d9c62dfa1b%7C8cbcddd9588d4e3b9c1e2367dbdf1740%7C0%7C0%7C637758723058571427%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=S8Wh4aTIFgpqYAeeHUDbeyb8tmNElO3Iscq4n8d0yuY%3D&reserved=0>, does SCHISM accept stations.in instead of station.in as station input file?

-
Reply to this email directly, view it on GitHub<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fschism-dev%2Fpyschism%2Fissues%2F33&data=04%7C01%7Cyjzhang%40vims.edu%7Ca0f86e11570441e61e0408d9c62dfa1b%7C8cbcddd9588d4e3b9c1e2367dbdf1740%7C0%7C0%7C637758723058571427%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=JU67ucA47Db25kriAt%2B6s6idDm8yj%2B2XWTtj6rgYBVw%3D&reserved=0>, or unsubscribe<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAFBKNZ5M55BRHGCRAMCLSSDUSNCC3ANCNFSM5KVCD3HQ&data=04%7C01%7Cyjzhang%40vims.edu%7Ca0f86e11570441e61e0408d9c62dfa1b%7C8cbcddd9588d4e3b9c1e2367dbdf1740%7C0%7C0%7C637758723058571427%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=Q5oBxCF9%2BhzPUuqTbXeOJiGfFvGyidjoeo%2FVh1PvXqE%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cyjzhang%40vims.edu%7Ca0f86e11570441e61e0408d9c62dfa1b%7C8cbcddd9588d4e3b9c1e2367dbdf1740%7C0%7C0%7C637758723058571427%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=rJVFwgcDqT2EwoOuGB2mbzor0Kk4gotySu0yxebtP98%3D&reserved=0> or Android<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cyjzhang%40vims.edu%7Ca0f86e11570441e61e0408d9c62dfa1b%7C8cbcddd9588d4e3b9c1e2367dbdf1740%7C0%7C0%7C637758723058571427%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=DO2isD%2BjGV0DCUj%2BTTYsW5k4uEWcOR2glOGoU8CX1vw%3D&reserved=0>.

**Comment by SorooshMani-NOAA** [comment]
This seems to have been fixed in 04db6377ebf93c4b3b1a0ab3bf40be66aeefe4e1
